# Generated by Django 5.1.4 on 2024-12-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('uni_id', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_num', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=30)),
                ('nic_num', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
